Add C()
gustavold/teste pull request #1
Opened 2021-02-10 19:09 UTC by gromero

Adding C(), please  review.

2021-02-10 19:11 UTC, gromero commented
@gustavold please review

2021-02-10 19:28 UTC, gustavold requested changes

2021-02-10 19:28 UTC, gustavold commented on main.c
> +
nem faz sentido.

2021-02-10 19:28 UTC, gustavold commented on main.c
> +    C();
tá errado

2021-02-10 19:37 UTC, gustavold requested changes

2021-02-10 19:37 UTC, gustavold commented on main.c
> +    printf("I'm C__\n");
it sucks

2021-02-18 14:18 UTC, closed without merging

2021-02-18 14:18 UTC, gromero commented
Teste feito : (